export const cell_dimension = 2;
export const WALL_COLOR = "rgb(52, 152, 219)";
export const CLEAR_COLOR = "rgb(255, 255, 255)";
export const UNDISCOVERED_COLOR = "rgb(255, 255, 255)";
export const DISCOVERED_COLOR = "rgb(113, 128, 147)";
export const EXPLORED_COLOR = "rgb(0, 0, 0)";
export const SOURCE_COLOR = "rgb(232, 65, 24)";
export const TARGET_COLOR = "rgb(76, 209, 55)";
export const PATH_COLOR = "rgb(140, 122, 230)";
export const BFS_DESCRIPTION = "<b>BFS: Breadth First Search</b><br>\n" +
    "<p><strong>Worst-Case Time Complexity: </strong>$$O(|V|+|E|)=O(b^d)$$</p>\n" +
    "<p><strong>Worst-Case Space Complexity: </strong>$$O(|V|)=O(b^d)$$</p>";
export const DFS_DESCRIPTION = "<b>DFS: Depth First Search</b><br>\n" +
    "<p><strong>Worst-Case Time Complexity: </strong>$$O(|V|+|E|)=O(b^d)$$</p>\n" +
    "<p><strong>Worst-Case Space Complexity: </strong>$$O(|V|)=O(bd)$$</p>";
export const A_STAR_DESCRIPTION = "<b>BFS: Breadth First Search</b><br>\n" +
    "<p><strong>Worst-Case Time Complexity: </strong>$$O(|E|)=O(b^d)$$</p>\n" +
    "<p><strong>Worst-Case Space Complexity: </strong>$$O(|V|)=O(b^d)$$</p>";